default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: penny_wise
  username: postgres
  password: admin
  host: localhost
  port: 5432


test:
  <<: *default
  database: penny_wise
  username: postgres
  password: admin
  host: localhost
  port: 5432


production:
  <<: *default
  database: penny_wise
  username: postgres
  password: <%= ENV['1234'] %>
  port: 5432